# Changes here will be overwritten by Copier
_src_path: ../copier-django-project/template/
copyright_date: '2022'
copyright_holder: Apexive.com OSS
copyright_holder_email: support@apexive.com
google_project: apexample
media_storage_cache_urls: true
media_storage_public: true
organisation: djangoflow
project_description: DjangoFlow Demo
project_name: apexample
repository_name: demo-django
use_precommit: true
