steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/[[ project_name ]]-django-base:$BRANCH_NAME', '-f', 'Dockerfile.jinja2', '.' ]
images:
- 'gcr.io/$PROJECT_ID/[[ project_name ]]-django-base:$BRANCH_NAME'
