steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/django-base:$BRANCH_NAME', '-f', 'Dockerfile', '.' ]
images:
- 'gcr.io/$PROJECT_ID/django-base:$BRANCH_NAME'
